import { useState } from 'react'
import { X } from 'lucide-react'
import { useQueryClient } from '@tanstack/react-query'
import { createAccount, updateAccount } from '../api/accounts'
import { parseToCents } from '../lib/money'

export function AccountModal({onClose, account}) {
  const queryClient=useQueryClient(); const editing=Boolean(account); const [type,setType]=useState(account?.type||'debit'); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);const opening=parseToCents(f.get('opening'));const limit=parseToCents(f.get('limit'));if(opening===null||(type==='credit'&&(limit===null||limit<0)))return setError('Use valid amounts with up to two decimal places.');setSaving(true);try{const data={name:f.get('name'),opening_balance_cents:opening,credit_limit_cents:type==='credit'?limit:undefined,statement_day:type==='credit'?Number(f.get('statement_day')):undefined,due_day:type==='credit'?Number(f.get('due_day')):undefined};if(editing)await updateAccount(account.id,data);else await createAccount({...data,type});await queryClient.invalidateQueries({queryKey:['accounts']});onClose()}catch(e){setError(e.message)}finally{setSaving(false)}}
  const opening=account?(Number(account.opening_balance_cents)/100).toFixed(2):'0.00';const limit=account?.credit_limit_cents!==undefined?(Number(account.credit_limit_cents)/100).toFixed(2):''
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{editing?'Edit account':'New account'}</h2><p className="section-description">{editing?'Update this account’s details and starting balance.':'Every place money can sit is one account.'}</p></div><button className="icon-button" type="button" onClick={onClose}><X/></button></div><div className="form-grid"><div className="field wide"><label>Account name</label><input name="name" defaultValue={account?.name||''} placeholder="e.g. BBVA Debit" required autoFocus/></div><div className="field"><label>Type</label>{editing?<input value={type} readOnly aria-label="Account type"/>:<select value={type} onChange={e=>setType(e.target.value)}>{['cash','savings','debit','credit','investment'].map(t=><option key={t}>{t}</option>)}</select>}</div><div className="field"><label>Opening balance</label><input name="opening" defaultValue={opening} inputMode="decimal" required/></div>{type==='credit'&&<><div className="field wide"><label>Credit limit</label><input name="limit" defaultValue={limit} inputMode="decimal" required/></div><div className="field"><label>Statement closes on</label><input name="statement_day" type="number" min="1" max="31" defaultValue={account?.statement_day||15} required/></div><div className="field"><label>Payment due on</label><input name="due_day" type="number" min="1" max="31" defaultValue={account?.due_day||5} required/></div></>}</div>{editing&&<p className="form-help">Account type cannot be changed after creation because it may have transaction history.</p>}{error&&<p className="error">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Create account'}</button></div></form></div>
}
