import { useState } from 'react'
import { X } from 'lucide-react'
import { useQueryClient } from '@tanstack/react-query'
import { createTransaction } from '../api/transactions'
import { useAccounts } from '../api/accounts'
import { useCategories } from '../api/insights'
import { parseToCents } from '../lib/money'
import { today } from '../lib/dates'

export function TransactionModal({ onClose }) {
  const queryClient=useQueryClient(); const {data:accounts=[]}=useAccounts(); const {data:categories=[]}=useCategories(); const [type,setType]=useState('expense'); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  async function submit(e) { e.preventDefault(); const form=new FormData(e.currentTarget); const amount=parseToCents(form.get('amount')); if(amount===null||amount<=0)return setError('Enter a positive amount with up to two decimal places.'); const data={type,amount_cents:amount,occurred_on:form.get('occurred_on'),from_account_id:form.get('from_account_id')||null,to_account_id:form.get('to_account_id')||null,category_id:form.get('category_id')||null,merchant:form.get('merchant'),note:form.get('note')};setSaving(true);setError('');try{await createTransaction(data);await queryClient.invalidateQueries({queryKey:['transactions']});await queryClient.invalidateQueries({queryKey:['accounts']});await queryClient.invalidateQueries({queryKey:['insights']});onClose()}catch(err){setError(err.message)}finally{setSaving(false)} }
  const accountSelect=(name,label)=><div className="field"><label>{label}</label><select name={name} required><option value="">Choose account</option>{accounts.filter(a=>!Number(a.is_archived)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Add transaction</h2><p className="section-description">Record money entering, leaving, or moving within your accounts.</p></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><div className="form-grid"><div className="field"><label>Type</label><select value={type} onChange={e=>setType(e.target.value)}><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option></select></div><div className="field"><label>Amount</label><input name="amount" placeholder="0.00" inputMode="decimal" required autoFocus/></div><div className="field"><label>Date</label><input name="occurred_on" type="date" defaultValue={today()} required/></div>{type!=='income'&&accountSelect('from_account_id','From account')}{type!=='expense'&&accountSelect('to_account_id','To account')}{type==='expense'&&<div className="field"><label>Category</label><select name="category_id"><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>}<div className={type==='transfer'?'field wide':'field'}><label>Merchant</label><input name="merchant" placeholder={type==='expense'?'e.g. Local grocery':'Optional'}/></div><div className="field wide"><label>Note</label><textarea name="note" rows="2" placeholder="Optional details"/></div></div>{error&&<p className="error">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={saving}>{saving?'Saving…':'Save transaction'}</button></div></form></div>
}
